languageCode = "en-us"
baseurl = "https://sytranvn.dev/hugo-pdf"
title = "Hugo PDF"
theme = ["hugo-coder", "hugo-pdf"]


[markup.highlight]
style = "github-dark"


colorScheme = "dark"
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []
