languageCode = "en-us"
baseurl = "https://sytranvn.dev/hugo-pdf"
title = "Hugo PDF"
theme = ["hugo-coder", "hugo-pdf"]


[markup.highlight]
style = "github-dark"

[params]
author = "Sy Tran Dung"
description = "Hugo PDF"
colorScheme = "dark"
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["hugo-pdf.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"
